# Simulation Params
## Robot parameters
simulation_speed: 1.0
target_robot_count: 10
obstacle_robot_count: 4
frame_rate: 30

## MAV parameters
vel_xy_p: 1.0
vel_xy_i: 0.0
vel_xy_d: 0.5
vel_xy_max: 2.0
vel_z_p: 2.0
vel_z_i: 0.5
vel_z_d: 1.0
vel_z_max: 0.25

## Robot Detection Params

# Debug Mode displays images and trackbars
debug_mode: true

# True uses webcam directly from opencv, false subscribes to camera/image_raw
use_webcam: true

# Morphological operations iterations for white filtering
pre_erosions: 5
dilations: 5
post_erosions: 5

# HSV filter parameters for the white part of the robot
h_min_w: 0
h_max_w: 256
s_min_w: 0
s_max_w: 256
v_min_w: 0
v_max_w: 256

# HSV filter parameters for the colored part of the robot
h_min_c: 0
h_max_c: 256
s_min_c: 0
s_max_c: 256
v_min_c: 0
v_max_C: 256

# Shape detection parameters
pre_blur: 2
canny_thresh1: 1
canny_thresh2: 1
canny_aperture: 3